# Step 1: Build your React app
FROM node:14 AS builder

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

RUN yarn build

# Step 2: Set up nginx server to serve your built React app
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

# If you need to customize nginx configuration, copy your nginx.conf file
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
